name: Feature request
description: Request a new feature
labels: ["feature :sparkles:"]
body:
  - type: markdown
    attributes:
      value: |
        1. Please fill the form below, this way we can analyse and fix the problem as fast as possible.
        2. If you are adding screenshots and/or videos, please do add it in English.
  - type: checkboxes
    attributes:
      label: Avoid duplicates
      description: Please ensure you've completed the following
      options:
        - label: I agree to follow the [Code of Conduct](https://github.com/specialaro/mgt2/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
          required: true
        - label: I have searched the [issues tracker](https://github.com/specialaro/mgt2/issues?q=is%3Aopen+is%3Aissue) for a feature request similar to mine, in vain
          required: true
  - type: textarea
    attributes:
      label: Problem description
      description: A clear and concise description of what the problem is.
      placeholder: |
        Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help visualize your problem
  - type: textarea
    attributes:
      label: Additional information
      description: Add any other context or screenshots about the feature request here.